Added gitpod

diff --git a/.gitpod.yml b/.gitpod.yml
--- a/.gitpod.yml
+++ b/.gitpod.yml
@@ -52,6 +52,14 @@ tasks:
           fi
           dotnet run --project giftcard-example
         ;;
+
+        "giving-example")
+          if [ -z ${ADYEN_HMAC_KEY+x} ] || [[ -z ${ADYEN_API_KEY+x} ]] || [[ -z ${ADYEN_CLIENT_KEY+x} ]] || [[ -z ${ADYEN_MERCHANT_ACCOUNT+x} ]]; then
+            echo "Expected environment variables not found. Please set the ADYEN_HMAC_KEY, ADYEN_API_KEY, ADYEN_CLIENT_KEY, ADYEN_MERCHANT_ACCOUNT environment variables in https://gitpod.io/variables and restart."
+            exit 1
+          fi
+          dotnet run --project giving-example
+        ;;
         
         "in-person-payments-example")
           if [ -z ${ADYEN_HMAC_KEY+x} ] || [[ -z ${ADYEN_API_KEY+x} ]] || [[ -z ${ADYEN_MERCHANT_ACCOUNT+x} ]] || [[ -z ${ADYEN_POS_POI_ID+x} ]]; then
