Added Integration-Example: Authorisation Adjustment (#91)
* Initial commit - Authorisation Adjustment
* Modified solution to follow advanced-checkoutflow and use manual capture + preauth in additionalData to make a payment of 249.99
* Add incremental/decremental/extend adjustment services
* Added capture
* Added reversals
* Added styling, frontend bindings & respective views
* Updated build.yml and e2e.yml to ignore running tests when readme is updated
* Added GIF Authorisation Adjustment Card

---------

Co-authored-by: Kwok He Chu <>

diff --git a/.gitpod.yml b/.gitpod.yml
--- a/.gitpod.yml
+++ b/.gitpod.yml
@@ -21,6 +21,14 @@ tasks:
     command: |
       # Check if environment variables are set in https://gitpod.io/variables and run the application based on specified $path.
       case "$path" in
+        "authorisation-adjustment-example")
+          if [ -z ${ADYEN_HMAC_KEY+x} ] || [[ -z ${ADYEN_API_KEY+x} ]] || [[ -z ${ADYEN_CLIENT_KEY+x} ]] || [[ -z ${ADYEN_MERCHANT_ACCOUNT+x} ]]; then
+            echo "Expected environment variables not found. Please set the ADYEN_HMAC_KEY, ADYEN_API_KEY, ADYEN_CLIENT_KEY, ADYEN_MERCHANT_ACCOUNT environment variables in https://gitpod.io/variables and restart."
+            exit 1
+          fi
+          dotnet run --project authorisation-adjustment-example
+        ;;
+        
         "checkout-example")
           if [ -z ${ADYEN_HMAC_KEY+x} ] || [[ -z ${ADYEN_API_KEY+x} ]] || [[ -z ${ADYEN_CLIENT_KEY+x} ]] || [[ -z ${ADYEN_MERCHANT_ACCOUNT+x} ]]; then
             echo "Expected environment variables not found. Please set the ADYEN_HMAC_KEY, ADYEN_API_KEY, ADYEN_CLIENT_KEY, ADYEN_MERCHANT_ACCOUNT environment variables in https://gitpod.io/variables and restart."
